language: node_js
node_js:
  - "11"
cache: yarn
script:
  - yarn lint
  - yarn test --watch=false --browsers=ChromeHeadless
  - npm install protractor -g
  - protractor --version
  - webdriver-update
  - webdriver-start
  - yarn ci-e2e
  - yarn build --prod
